/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace ZenChainDiary {
  export type DiaryEntryStruct = {
    id: BigNumberish;
    author: AddressLike;
    moodScore: BytesLike;
    stressScore: BytesLike;
    sleepQuality: BytesLike;
    moodTags: BytesLike;
    diaryTextHash: BytesLike;
    timestamp: BigNumberish;
    isPublic: boolean;
    isDeleted: boolean;
  };

  export type DiaryEntryStructOutput = [
    id: bigint,
    author: string,
    moodScore: string,
    stressScore: string,
    sleepQuality: string,
    moodTags: string,
    diaryTextHash: string,
    timestamp: bigint,
    isPublic: boolean,
    isDeleted: boolean
  ] & {
    id: bigint;
    author: string;
    moodScore: string;
    stressScore: string;
    sleepQuality: string;
    moodTags: string;
    diaryTextHash: string;
    timestamp: bigint;
    isPublic: boolean;
    isDeleted: boolean;
  };

  export type UserProfileStruct = {
    registered: boolean;
    registeredAt: BigNumberish;
    totalEntries: BytesLike;
    sumMood: BytesLike;
    sumStress: BytesLike;
    sumSleep: BytesLike;
    allowPublic: boolean;
  };

  export type UserProfileStructOutput = [
    registered: boolean,
    registeredAt: bigint,
    totalEntries: string,
    sumMood: string,
    sumStress: string,
    sumSleep: string,
    allowPublic: boolean
  ] & {
    registered: boolean;
    registeredAt: bigint;
    totalEntries: string;
    sumMood: string;
    sumStress: string;
    sumSleep: string;
    allowPublic: boolean;
  };
}

export interface ZenChainDiaryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "deleteEntry"
      | "entries"
      | "getEntry"
      | "getEntryMoodScore"
      | "getEntryMoodTags"
      | "getEntrySleepQuality"
      | "getEntryStressScore"
      | "getEntryTextHash"
      | "getPublicEntryCount"
      | "getUserEntries"
      | "getUserEntryCount"
      | "getUserProfile"
      | "profiles"
      | "protocolId"
      | "publicEntryIds"
      | "submitEntry"
      | "totalEntryCount"
      | "updatePrivacySetting"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "EntryDeleted"
      | "EntrySubmitted"
      | "PrivacySettingUpdated"
      | "UserRegistered"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "deleteEntry",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "entries",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getEntry",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getEntryMoodScore",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getEntryMoodTags",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getEntrySleepQuality",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getEntryStressScore",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getEntryTextHash",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getPublicEntryCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getUserEntries",
    values: [AddressLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getUserEntryCount",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getUserProfile",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "profiles",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "protocolId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "publicEntryIds",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "submitEntry",
    values: [
      BytesLike,
      BytesLike,
      BytesLike,
      BytesLike,
      BytesLike,
      BytesLike,
      BytesLike,
      BytesLike,
      BytesLike,
      BytesLike,
      boolean
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "totalEntryCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "updatePrivacySetting",
    values: [boolean]
  ): string;

  decodeFunctionResult(
    functionFragment: "deleteEntry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "entries", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getEntry", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getEntryMoodScore",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getEntryMoodTags",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getEntrySleepQuality",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getEntryStressScore",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getEntryTextHash",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPublicEntryCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserEntries",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserEntryCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserProfile",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "profiles", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "protocolId", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "publicEntryIds",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "submitEntry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalEntryCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updatePrivacySetting",
    data: BytesLike
  ): Result;
}

export namespace EntryDeletedEvent {
  export type InputTuple = [user: AddressLike, entryId: BigNumberish];
  export type OutputTuple = [user: string, entryId: bigint];
  export interface OutputObject {
    user: string;
    entryId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EntrySubmittedEvent {
  export type InputTuple = [
    user: AddressLike,
    entryId: BigNumberish,
    timestamp: BigNumberish,
    isPublic: boolean
  ];
  export type OutputTuple = [
    user: string,
    entryId: bigint,
    timestamp: bigint,
    isPublic: boolean
  ];
  export interface OutputObject {
    user: string;
    entryId: bigint;
    timestamp: bigint;
    isPublic: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PrivacySettingUpdatedEvent {
  export type InputTuple = [user: AddressLike, allowPublic: boolean];
  export type OutputTuple = [user: string, allowPublic: boolean];
  export interface OutputObject {
    user: string;
    allowPublic: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UserRegisteredEvent {
  export type InputTuple = [user: AddressLike, timestamp: BigNumberish];
  export type OutputTuple = [user: string, timestamp: bigint];
  export interface OutputObject {
    user: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ZenChainDiary extends BaseContract {
  connect(runner?: ContractRunner | null): ZenChainDiary;
  waitForDeployment(): Promise<this>;

  interface: ZenChainDiaryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  deleteEntry: TypedContractMethod<
    [entryId: BigNumberish],
    [void],
    "nonpayable"
  >;

  entries: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        string,
        string,
        string,
        string,
        string,
        string,
        bigint,
        boolean,
        boolean
      ] & {
        id: bigint;
        author: string;
        moodScore: string;
        stressScore: string;
        sleepQuality: string;
        moodTags: string;
        diaryTextHash: string;
        timestamp: bigint;
        isPublic: boolean;
        isDeleted: boolean;
      }
    ],
    "view"
  >;

  getEntry: TypedContractMethod<
    [entryId: BigNumberish],
    [ZenChainDiary.DiaryEntryStructOutput],
    "view"
  >;

  getEntryMoodScore: TypedContractMethod<
    [entryId: BigNumberish],
    [string],
    "view"
  >;

  getEntryMoodTags: TypedContractMethod<
    [entryId: BigNumberish],
    [string],
    "view"
  >;

  getEntrySleepQuality: TypedContractMethod<
    [entryId: BigNumberish],
    [string],
    "view"
  >;

  getEntryStressScore: TypedContractMethod<
    [entryId: BigNumberish],
    [string],
    "view"
  >;

  getEntryTextHash: TypedContractMethod<
    [entryId: BigNumberish],
    [string],
    "view"
  >;

  getPublicEntryCount: TypedContractMethod<[], [bigint], "view">;

  getUserEntries: TypedContractMethod<
    [user: AddressLike, offset: BigNumberish, limit: BigNumberish],
    [bigint[]],
    "view"
  >;

  getUserEntryCount: TypedContractMethod<[user: AddressLike], [bigint], "view">;

  getUserProfile: TypedContractMethod<
    [user: AddressLike],
    [ZenChainDiary.UserProfileStructOutput],
    "view"
  >;

  profiles: TypedContractMethod<
    [arg0: AddressLike],
    [
      [boolean, bigint, string, string, string, string, boolean] & {
        registered: boolean;
        registeredAt: bigint;
        totalEntries: string;
        sumMood: string;
        sumStress: string;
        sumSleep: string;
        allowPublic: boolean;
      }
    ],
    "view"
  >;

  protocolId: TypedContractMethod<[], [bigint], "view">;

  publicEntryIds: TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;

  submitEntry: TypedContractMethod<
    [
      encryptedMood: BytesLike,
      moodProof: BytesLike,
      encryptedStress: BytesLike,
      stressProof: BytesLike,
      encryptedSleep: BytesLike,
      sleepProof: BytesLike,
      encryptedTags: BytesLike,
      tagsProof: BytesLike,
      encryptedTextHash: BytesLike,
      textProof: BytesLike,
      isPublic: boolean
    ],
    [bigint],
    "nonpayable"
  >;

  totalEntryCount: TypedContractMethod<[], [bigint], "view">;

  updatePrivacySetting: TypedContractMethod<
    [allowPublic: boolean],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "deleteEntry"
  ): TypedContractMethod<[entryId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "entries"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        string,
        string,
        string,
        string,
        string,
        string,
        bigint,
        boolean,
        boolean
      ] & {
        id: bigint;
        author: string;
        moodScore: string;
        stressScore: string;
        sleepQuality: string;
        moodTags: string;
        diaryTextHash: string;
        timestamp: bigint;
        isPublic: boolean;
        isDeleted: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getEntry"
  ): TypedContractMethod<
    [entryId: BigNumberish],
    [ZenChainDiary.DiaryEntryStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getEntryMoodScore"
  ): TypedContractMethod<[entryId: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "getEntryMoodTags"
  ): TypedContractMethod<[entryId: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "getEntrySleepQuality"
  ): TypedContractMethod<[entryId: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "getEntryStressScore"
  ): TypedContractMethod<[entryId: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "getEntryTextHash"
  ): TypedContractMethod<[entryId: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "getPublicEntryCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getUserEntries"
  ): TypedContractMethod<
    [user: AddressLike, offset: BigNumberish, limit: BigNumberish],
    [bigint[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "getUserEntryCount"
  ): TypedContractMethod<[user: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getUserProfile"
  ): TypedContractMethod<
    [user: AddressLike],
    [ZenChainDiary.UserProfileStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "profiles"
  ): TypedContractMethod<
    [arg0: AddressLike],
    [
      [boolean, bigint, string, string, string, string, boolean] & {
        registered: boolean;
        registeredAt: bigint;
        totalEntries: string;
        sumMood: string;
        sumStress: string;
        sumSleep: string;
        allowPublic: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "protocolId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "publicEntryIds"
  ): TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "submitEntry"
  ): TypedContractMethod<
    [
      encryptedMood: BytesLike,
      moodProof: BytesLike,
      encryptedStress: BytesLike,
      stressProof: BytesLike,
      encryptedSleep: BytesLike,
      sleepProof: BytesLike,
      encryptedTags: BytesLike,
      tagsProof: BytesLike,
      encryptedTextHash: BytesLike,
      textProof: BytesLike,
      isPublic: boolean
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "totalEntryCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "updatePrivacySetting"
  ): TypedContractMethod<[allowPublic: boolean], [void], "nonpayable">;

  getEvent(
    key: "EntryDeleted"
  ): TypedContractEvent<
    EntryDeletedEvent.InputTuple,
    EntryDeletedEvent.OutputTuple,
    EntryDeletedEvent.OutputObject
  >;
  getEvent(
    key: "EntrySubmitted"
  ): TypedContractEvent<
    EntrySubmittedEvent.InputTuple,
    EntrySubmittedEvent.OutputTuple,
    EntrySubmittedEvent.OutputObject
  >;
  getEvent(
    key: "PrivacySettingUpdated"
  ): TypedContractEvent<
    PrivacySettingUpdatedEvent.InputTuple,
    PrivacySettingUpdatedEvent.OutputTuple,
    PrivacySettingUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "UserRegistered"
  ): TypedContractEvent<
    UserRegisteredEvent.InputTuple,
    UserRegisteredEvent.OutputTuple,
    UserRegisteredEvent.OutputObject
  >;

  filters: {
    "EntryDeleted(address,uint256)": TypedContractEvent<
      EntryDeletedEvent.InputTuple,
      EntryDeletedEvent.OutputTuple,
      EntryDeletedEvent.OutputObject
    >;
    EntryDeleted: TypedContractEvent<
      EntryDeletedEvent.InputTuple,
      EntryDeletedEvent.OutputTuple,
      EntryDeletedEvent.OutputObject
    >;

    "EntrySubmitted(address,uint256,uint256,bool)": TypedContractEvent<
      EntrySubmittedEvent.InputTuple,
      EntrySubmittedEvent.OutputTuple,
      EntrySubmittedEvent.OutputObject
    >;
    EntrySubmitted: TypedContractEvent<
      EntrySubmittedEvent.InputTuple,
      EntrySubmittedEvent.OutputTuple,
      EntrySubmittedEvent.OutputObject
    >;

    "PrivacySettingUpdated(address,bool)": TypedContractEvent<
      PrivacySettingUpdatedEvent.InputTuple,
      PrivacySettingUpdatedEvent.OutputTuple,
      PrivacySettingUpdatedEvent.OutputObject
    >;
    PrivacySettingUpdated: TypedContractEvent<
      PrivacySettingUpdatedEvent.InputTuple,
      PrivacySettingUpdatedEvent.OutputTuple,
      PrivacySettingUpdatedEvent.OutputObject
    >;

    "UserRegistered(address,uint256)": TypedContractEvent<
      UserRegisteredEvent.InputTuple,
      UserRegisteredEvent.OutputTuple,
      UserRegisteredEvent.OutputObject
    >;
    UserRegistered: TypedContractEvent<
      UserRegisteredEvent.InputTuple,
      UserRegisteredEvent.OutputTuple,
      UserRegisteredEvent.OutputObject
    >;
  };
}
